[package]
name = "wcr"
version = "0.1.0"
edition = "2021"

[dependencies]
assert_cmd = "2.0.16"
clap = "4.5.23"
predicates = "3.1.3"

[dev-dependencies]
anyhow = "1.0.95"
pretty_assertions = "1.4.1"
rand = "0.8.5"
