[package]
name = "headr"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
anyhow = "1.0.95"
assert_cmd = "2.0.16"
predicates = "3.1.3"
pretty_assertions = "1.4.1"
rand = "0.8.5"
